// <auto-generated />
using System;
using BijouterieApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BijouterieApp.Data.Migrations
{
    [DbContext(typeof(BijouterieDbContext))]
    [Migration("20260724193813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BijouterieApp.Core.Entities.Bijou", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Matiere")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PoidsGrammes")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantiteStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Bijoux", (string)null);
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroClient")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonction")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Employes", (string)null);
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.LigneVente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BijouId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BijouId");

                    b.HasIndex("VenteId");

                    b.ToTable("LigneVentes", (string)null);
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BijouId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BijouId");

                    b.HasIndex("EmployeId");

                    b.ToTable("MouvementsStock", (string)null);
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Vente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Remise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeId");

                    b.ToTable("Ventes", (string)null);
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Bijou", b =>
                {
                    b.HasOne("BijouterieApp.Core.Entities.Categorie", "Categorie")
                        .WithMany("Bijoux")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.LigneVente", b =>
                {
                    b.HasOne("BijouterieApp.Core.Entities.Bijou", "Bijou")
                        .WithMany("LigneVentes")
                        .HasForeignKey("BijouId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BijouterieApp.Core.Entities.Vente", "Vente")
                        .WithMany("LigneVentes")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bijou");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.MouvementStock", b =>
                {
                    b.HasOne("BijouterieApp.Core.Entities.Bijou", "Bijou")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("BijouId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BijouterieApp.Core.Entities.Employe", "Employe")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bijou");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Vente", b =>
                {
                    b.HasOne("BijouterieApp.Core.Entities.Client", "Client")
                        .WithMany("Ventes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BijouterieApp.Core.Entities.Employe", "Employe")
                        .WithMany("Ventes")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Bijou", b =>
                {
                    b.Navigation("LigneVentes");

                    b.Navigation("MouvementsStock");
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Categorie", b =>
                {
                    b.Navigation("Bijoux");
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Client", b =>
                {
                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Employe", b =>
                {
                    b.Navigation("MouvementsStock");

                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("BijouterieApp.Core.Entities.Vente", b =>
                {
                    b.Navigation("LigneVentes");
                });
#pragma warning restore 612, 618
        }
    }
}
